<a href="https://colab.research.google.com/github/samriddhisingh05/1BM23CS295_Samriddhi_Singh_ML_Lab/blob/main/1BM23CS295_Lab_4_Decision_Tree_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
data = pd.read_csv("iriss.csv")

# Features and Target
X = data.drop("species", axis=1)
y = data["species"]

# Train Test Split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# -------------------------------
# ID3 Algorithm (Entropy)
# -------------------------------
id3_model = DecisionTreeClassifier(criterion="entropy")

id3_model.fit(X_train, y_train)

y_pred_id3 = id3_model.predict(X_test)

print("ID3 Accuracy:", accuracy_score(y_test, y_pred_id3))
print("ID3 Confusion Matrix:\n", confusion_matrix(y_test, y_pred_id3))


# -------------------------------
# CART Algorithm (Gini)
# -------------------------------
cart_model = DecisionTreeClassifier(criterion="gini")

cart_model.fit(X_train, y_train)

y_pred_cart = cart_model.predict(X_test)

print("\nCART Accuracy:", accuracy_score(y_test, y_pred_cart))
print("CART Confusion Matrix:\n", confusion_matrix(y_test, y_pred_cart))

ID3 Accuracy: 1.0
ID3 Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

CART Accuracy: 1.0
CART Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load dataset
data = pd.read_csv("drug.csv")

# Convert categorical data to numerical using LabelEncoder
le = LabelEncoder()

for column in data.columns:
    data[column] = le.fit_transform(data[column])

# Features and target
X = data.drop("Drug", axis=1)
y = data["Drug"]

# Train-Test Split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# -------------------------
# ID3 Algorithm (Entropy)
# -------------------------
id3 = DecisionTreeClassifier(criterion="entropy")

id3.fit(X_train, y_train)

y_pred_id3 = id3.predict(X_test)

print("ID3 Accuracy:", accuracy_score(y_test, y_pred_id3))
print("ID3 Confusion Matrix:\n", confusion_matrix(y_test, y_pred_id3))


# -------------------------
# CART Algorithm (Gini)
# -------------------------
cart = DecisionTreeClassifier(criterion="gini")

cart.fit(X_train, y_train)

y_pred_cart = cart.predict(X_test)

print("\nCART Accuracy:", accuracy_score(y_test, y_pred_cart))
print("CART Confusion Matrix:\n", confusion_matrix(y_test, y_pred_cart))

ID3 Accuracy: 1.0
ID3 Confusion Matrix:
 [[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]

CART Accuracy: 1.0
CART Confusion Matrix:
 [[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]


In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Load dataset
data = pd.read_csv("petrol_consumption.csv")

# Features and target
X = data.drop("Petrol_Consumption", axis=1)
y = data["Petrol_Consumption"]

# Train-Test Split (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Build Regression Tree
model = DecisionTreeRegressor()

model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)
print("Root Mean Squared Error:", rmse)

Mean Absolute Error: 94.3
Mean Squared Error: 17347.7
Root Mean Squared Error: 131.7106677532234
